# Generated by Django 4.1.1 on 2022-11-19 23:33

import core_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=core_api.models.upload_to),
        ),
    ]
