# Generated by Django 4.1.1 on 2022-11-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_api', '0002_core_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='latitude',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='core',
            name='longitude',
            field=models.DecimalField(decimal_places=15, max_digits=30, null=True),
        ),
    ]
